#!/bin/zsh

VERSION=0.3.0

function uninstall {
    TMP_DIR=$(mktemp -d)
    TMP_FILE=$(mktemp)
    rm $TMP_FILE
    TMP_PKG=$TMP_FILE.pkg

    pkgbuild --root $TMP_DIR --identifier $1 $TMP_PKG > /dev/null
    rmdir $TMP_DIR
    sudo installer -pkg $TMP_PKG -target / 2>&1 > /dev/null
    if [ $? = 0 ]
    then
        sudo pkgutil --forget $1 2>&1 > /dev/null
        echo '\e[32msuccess\e[0m'
    else
        echo '\e[31mfailed\e[0m'
    fi
    rm $TMP_PKG
}

if [ ! -z $1 ]
then
    if [ $1 = '-h' -o $1 = '--help' ]
    then
        echo 'Usage: pkg_remove <PKG_ID> ...'
        exit
    elif [ $1 = '-v' -o $1 = '--version' ]
    then
        printf 'pkg_remove version %s\n' $VERSION
        exit
    fi
else
    echo 'Usage: pkg_remove <PKG_ID>'
    exit
fi

for PKG in $@
do
    printf 'uninstalling \e[32m%s\e[0m\n' $PKG
    uninstall $PKG
done
