#!/bin/zsh

uninstall() {
    TMP_DIR=$(mktemp -d)

    pkgbuild --root $TMP_DIR --identifier $1 uninstall.pkg
    sudo installer -pkg uninstall.pkg -target /
    if [ $? = 0 ]
    then
        sudo pkgutil --forget $1
    else
        echo $1 uninstallation failed.
    fi
    rm uninstall.pkg
    rmdir $TMP_DIR
}

for PKG in $@
do
    uninstall $PKG
done
